spring:
    application:
        name: mebookapi
    
    profiles:
        active: dev

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${DB_USER}
        password: ${DB_PASS}
        url: ${DB_URL}
    
logging:
    level:
        root: INFO
    